Prepare for automation

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1,130 +1,13 @@
 format_version: 1.1.0
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
-
+project_type: ""
+trigger_map:
+- pull_request_source_branch: '*'
+  pull_request_target_branch: master
+  workflow: audit-this-step
+- tag: '*'
+  workflow: share-this-step
 workflows:
-  test:
-    steps:
-    - change-workdir:
-        title: Switch working dir to test / fixture dir
-        description: |-
-          To prevent step testing issues, like referencing relative
-          files with just './some-file' in the step's code, which would
-          work for testing the step from this directory directly
-          but would break if the step is included in another `bitrise.yml`.
-        inputs:
-        - path: ./fixture
-        - is_create_path: false
-    - script:
-        title: Reset fields
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -e
-
-            envman unset --key "BUNDLE_ID"
-            envman unset --key "SEARCH_PATH"
-    - path::./:
-        title: Step Test
-        description: ''
-        inputs:
-        - xcode_project_path: "Test/Test.xcodeproj"
-        - target: Test
-        - configuration: Release
-        - xcode_setting_key: PRODUCT_BUNDLE_IDENTIFIER | LD_RUNPATH_SEARCH_PATHS
-        - target_variable: BUNDLE_ID  | SEARCH_PATH
-    - script:
-        title: Validate fields
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -e
-
-            if [[ "${BUNDLE_ID}" == 'test.Test' ]]; then
-              echo "Valid BUNDLE_ID"
-            else
-              echo "Invalid BUNDLE_ID value"
-              exit 1
-            fi
-
-            if [[ "${SEARCH_PATH}" == '$(inherited) @executable_path/Frameworks' ]]; then
-              echo "Valid SEARCH_PATH"
-            else
-              echo "Invalid SEARCH_PATH value"
-              exit 1
-            fi
-    - change-workdir:
-        title: Switch working dir to test / non_gemfile_fixture dir
-        run_if: 'true'
-        description: |-
-          To prevent step testing issues, like referencing relative
-          files with just './some-file' in the step's code, which would
-          work for testing the step from this directory directly
-          but would break if the step is included in another `bitrise.yml`.
-        inputs:
-        - path: '..'
-        - is_create_path: false
-    - change-workdir:
-        title: Switch working dir to test / non_gemfile_fixture dir
-        description: |-
-          To prevent step testing issues, like referencing relative
-          files with just './some-file' in the step's code, which would
-          work for testing the step from this directory directly
-          but would break if the step is included in another `bitrise.yml`.
-        inputs:
-        - path: ./non_gemfile_fixture
-        - is_create_path: false
-    - script:
-        title: Reset fields
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -e
-
-            envman unset --key "BUNDLE_ID"
-            envman unset --key "SEARCH_PATH"
-    - path::./:
-        title: Step Test
-        description: ''
-        inputs:
-        - xcode_project_path: "Test/Test.xcodeproj"
-        - target: Test
-        - configuration: Release
-        - xcode_setting_key: PRODUCT_BUNDLE_IDENTIFIER | LD_RUNPATH_SEARCH_PATHS
-        - target_variable: BUNDLE_ID  | SEARCH_PATH
-    - script:
-        title: Validate fields
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -e
-
-            if [[ "${BUNDLE_ID}" == 'test.Test' ]]; then
-              echo "Valid BUNDLE_ID"
-            else
-              echo "Invalid BUNDLE_ID value"
-              exit 1
-            fi
-
-            if [[ "${SEARCH_PATH}" == '$(inherited) @executable_path/Frameworks' ]]; then
-              echo "Valid SEARCH_PATH"
-            else
-              echo "Invalid SEARCH_PATH value"
-              exit 1
-            fi
-    - change-workdir:
-        title: Switch working dir to test / non_gemfile_fixture dir
-        run_if: 'true'
-        description: |-
-          To prevent step testing issues, like referencing relative
-          files with just './some-file' in the step's code, which would
-          work for testing the step from this directory directly
-          but would break if the step is included in another `bitrise.yml`.
-        inputs:
-        - path: '..'
-        - is_create_path: false
-          
-  # ----------------------------------------------------------------
-  # --- workflows to Share this step into a Step Library
   audit-this-step:
     before_run:
     - test
@@ -135,14 +18,7 @@ workflows:
             #!/bin/bash
             set -ex
             stepman audit --step-yml ./step.yml
-
   share-this-step:
-    envs:
-      # if you want to share this step into a StepLib
-      - MY_STEPLIB_REPO_FORK_GIT_URL: $MY_STEPLIB_REPO_FORK_GIT_URL
-      - STEP_ID_IN_STEPLIB: 'extract-xcode-settings'
-      - STEP_GIT_VERION_TAG_TO_SHARE: $STEP_GIT_VERION_TAG_TO_SHARE
-      - STEP_GIT_CLONE_URL: $STEP_GIT_CLONE_URL
     description: |-
       If this is the first time you try to share a Step you should
       first call: $ bitrise share
@@ -166,6 +42,11 @@ workflows:
       the way described in the guide printed at the end of the process.
     before_run:
     - audit-this-step
+    envs:
+    - MY_STEPLIB_REPO_FORK_GIT_URL: $MY_STEPLIB_REPO_FORK_GIT_URL
+    - STEP_ID_IN_STEPLIB: extract-xcode-settings
+    - STEP_GIT_VERION_TAG_TO_SHARE: $BITRISE_GIT_TAG
+    - STEP_GIT_CLONE_URL: $STEP_GIT_CLONE_URL
     steps:
     - script:
         inputs:
@@ -175,3 +56,123 @@ workflows:
             bitrise share start -c ${MY_STEPLIB_REPO_FORK_GIT_URL}
             bitrise share create --stepid ${STEP_ID_IN_STEPLIB} --tag ${STEP_GIT_VERION_TAG_TO_SHARE} --git ${STEP_GIT_CLONE_URL}
             bitrise share finish
+  test:
+    steps:
+    - change-workdir:
+        title: Switch working dir to test / fixture dir
+        description: |-
+          To prevent step testing issues, like referencing relative
+          files with just './some-file' in the step's code, which would
+          work for testing the step from this directory directly
+          but would break if the step is included in another `bitrise.yml`.
+        inputs:
+        - path: ./fixture
+        - is_create_path: false
+    - script:
+        title: Reset fields
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -e
+
+            envman unset --key "BUNDLE_ID"
+            envman unset --key "SEARCH_PATH"
+    - path::./:
+        title: Step Test
+        description: ""
+        inputs:
+        - xcode_project_path: Test/Test.xcodeproj
+        - target: Test
+        - configuration: Release
+        - xcode_setting_key: PRODUCT_BUNDLE_IDENTIFIER | LD_RUNPATH_SEARCH_PATHS
+        - target_variable: BUNDLE_ID  | SEARCH_PATH
+    - script:
+        title: Validate fields
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -e
+
+            if [[ "${BUNDLE_ID}" == 'test.Test' ]]; then
+              echo "Valid BUNDLE_ID"
+            else
+              echo "Invalid BUNDLE_ID value"
+              exit 1
+            fi
+
+            if [[ "${SEARCH_PATH}" == '$(inherited) @executable_path/Frameworks' ]]; then
+              echo "Valid SEARCH_PATH"
+            else
+              echo "Invalid SEARCH_PATH value"
+              exit 1
+            fi
+    - change-workdir:
+        title: Switch working dir to test / non_gemfile_fixture dir
+        description: |-
+          To prevent step testing issues, like referencing relative
+          files with just './some-file' in the step's code, which would
+          work for testing the step from this directory directly
+          but would break if the step is included in another `bitrise.yml`.
+        run_if: "true"
+        inputs:
+        - path: ..
+        - is_create_path: false
+    - change-workdir:
+        title: Switch working dir to test / non_gemfile_fixture dir
+        description: |-
+          To prevent step testing issues, like referencing relative
+          files with just './some-file' in the step's code, which would
+          work for testing the step from this directory directly
+          but would break if the step is included in another `bitrise.yml`.
+        inputs:
+        - path: ./non_gemfile_fixture
+        - is_create_path: false
+    - script:
+        title: Reset fields
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -e
+
+            envman unset --key "BUNDLE_ID"
+            envman unset --key "SEARCH_PATH"
+    - path::./:
+        title: Step Test
+        description: ""
+        inputs:
+        - xcode_project_path: Test/Test.xcodeproj
+        - target: Test
+        - configuration: Release
+        - xcode_setting_key: PRODUCT_BUNDLE_IDENTIFIER | LD_RUNPATH_SEARCH_PATHS
+        - target_variable: BUNDLE_ID  | SEARCH_PATH
+    - script:
+        title: Validate fields
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -e
+
+            if [[ "${BUNDLE_ID}" == 'test.Test' ]]; then
+              echo "Valid BUNDLE_ID"
+            else
+              echo "Invalid BUNDLE_ID value"
+              exit 1
+            fi
+
+            if [[ "${SEARCH_PATH}" == '$(inherited) @executable_path/Frameworks' ]]; then
+              echo "Valid SEARCH_PATH"
+            else
+              echo "Invalid SEARCH_PATH value"
+              exit 1
+            fi
+    - change-workdir:
+        title: Switch working dir to test / non_gemfile_fixture dir
+        description: |-
+          To prevent step testing issues, like referencing relative
+          files with just './some-file' in the step's code, which would
+          work for testing the step from this directory directly
+          but would break if the step is included in another `bitrise.yml`.
+        run_if: "true"
+        inputs:
+        - path: ..
+        - is_create_path: false
